spring.application.name=paymentservice

server.port=8084

# Note: If your local Oracle SID is different (like ORCLPDB1 or FREE), change 'XE' to your SID.
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=system
spring.datasource.password=system123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.format_sql=true

# Custom Dialect Configuration - Explicitly setting this prevents Hibernate from attempting 
# to query the database metadata on startup just to determine the dialect.
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Logging Configuration
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - [%X{correlationId}] - [%X{paymentId}] - %msg%n
